from .depth_nodes import DEPTH_NODE_CLASS_MAPPINGS, DEPTH_NODE_DISPLAY_NAME_MAPPINGS
from .filename_nodes import FILENAME_NODE_CLASS_MAPPINGS, FILENAME_NODE_DISPLAY_NAME_MAPPINGS
from .logic_nodes import LOGIC_NODE_CLASS_MAPPINGS, LOGIC_NODE_DISPLAY_NAME_MAPPINGS
from .mask_nodes import MASK_NODE_CLASS_MAPPINGS, MASK_NODE_DISPLAY_NAME_MAPPINGS
from .seamless import SEAMLESS_NODE_CLASS_MAPPINGS, SEAMLESS_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(SEAMLESS_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(DEPTH_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MASK_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(LOGIC_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(FILENAME_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(SEAMLESS_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(DEPTH_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MASK_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(LOGIC_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(FILENAME_NODE_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "./web"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
